
DROP TABLE IF EXISTS Authors;
CREATE TABLE Authors
(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS Books;

CREATE TABLE Books
(
    Id INT PRIMARY KEY AUTO_INCREMENT,
    AuthorId INT,
    Title VARCHAR(50) NOT NULL,
    FOREIGN KEY (AuthorId)  REFERENCES Authors (Id)
);
